### ISSUE TITLE
SZDAUT

### ISSUE THREAD

**Issue by chpollin** [chpollin/SZD#21]
- [x] in google chrome werden die bezeichnungen der icons unten nicht korrekt angezeigt, bei safari funktionieren sie

- [x] bei szdaut.563 rutscht das komma an „Berlin“ in die nächste zeile. bitte auch bei anderen prüfen!

**Comment by limazangerl** [comment]
ist das noch aktuell? wenn ja und schnell zu ändern, bitte erledigen, sonst würde ich es hintanstellen
