### ISSUE TITLE
SZDBIB

### ISSUE THREAD

**Issue by chpollin** [chpollin/SZD#23]
- [x] Privatbesitz, USA, auszeichnen, SZDBIB.763

- [x] Feld „Publication Details“: Spalte „Verlagsort“ muss aus engl. Tabelle generiert werden, weil sie auch engl.-sprachige Daten enthält, z.B. „[et al.]“
(Bsp. SZDBIB.79)

- [x] Feld „Publication Details“: Spalte „Verlag“ muss aus engl. Tabelle generiert werden, weil sie auch unterschiedliche engl.-sprachige Daten enthält (nicht nur Ortsbezeichnungen)

**Ansicht Suchergebnisse:**

- [x] Feld „Umfang/Einband“ bzw. „Physical Description“: Punkt zwischen Seitenzahl und Format fehlt, wenn nicht "illustriert" bzw. „illustrated“ daneben steht. bitte ergänzen
Feld „Umfang/Einband“ bzw. „Physical Description“: Doppelpunkt zwischen beiden Wörtern „Blatt illustriert“ bzw. „leaves illustrat

**Comment by revilo1014** [comment]
@chpollin @stephanmatt @revilo1014 

bei einträgen, die nicht nur eine einfache jahreszahl als angabe haben, werden in der liste hintereinander die deutschen und englischen angaben zum datum angezeigt, beispiele: 
SZDBIB.1250 »Momentos estelares de la humanidad | um 1935 ca. 1935« 
SZDBIB.1003 »Codex Manesse | 1925-1927 1925-1927«

**Comment by limazangerl** [comment]
@revilo1014 Hier müsstest Du bitte noch die Liste durchsehen, was aus deiner Sicht noch dringend zu erledigen wäre. Danke!

**Comment by chpollin** [comment]
@ Privatbesitz, USA, auszeichnen, SZDBIB.763
Nicht notwendig, da im Feld "Nachbesitzer/in" nie ein Link steht, sondern immer nur bei "Heutiger Standort".
