### ISSUE TITLE
Briefverzeichnis

### ISSUE THREAD

**Issue by chpollin** [chpollin/SZD#28]
- [x] TEI Modell + correspDesc; model
- [x] Fredonia - Excel To XML/TEI
- [x] Webview ~ SZDBIB, SZDMSK etc
- [ ] "Briefverzeichnis" add persons to SZDPER aufnehmen - [Excel](https://docs.google.com/spreadsheets/d/1VX9XBH2yQV5TygdRpWLNjkaEObuQ4Hd1eMSyIo6lgxo/edit?usp=sharing ) @chpollin 
- [ ] finalizing google spreadsheet to XML/TEI @chpollin

**Comment by limazangerl** [comment]
Beides Priorität und ist ja auch schon mit Deadline für Abgabe an dich am 15. September vorgesehen
