### ISSUE TITLE
SZDLEB

### ISSUE THREAD

**Issue by limazangerl** [chpollin/SZD#3]
- [x] Groß/Kleinschreibung vgl. Werke und siehe Hauptbuch (writing materials in Kleinschreibung?)
- [x] Signaturen prüfen und ggf. ändern
- [x] fehlenden engl. Übersetzungen ergänzen
- [x] Unterüberschriften / Einheitstitel lang:en ergänzen
- [ ] ggf. Personensuchworte ergänzen
- [x] Sprachen in TEI anpassen
- [x] Ein Komma nach <term type="objecttyp">Notizbuch</term> setzen: <term type="objecttyp">Notizbuch</term>**,**

**Comment by stefzi** [comment]
- [ ] Lebensdokumente Marbach - noch Personen im Kommentarfeld zu einigen Einträgen erwähnt, die ggf. in den Personenindex aufgenommen und jeweils in den Einträgen selbst noch entsprechend ergänzt werden müssen (person/person affected) @limazangerl 
- [ ] gewählte Titel überprüfen und ggf. abändern (vielfach assigned) @limazangerl

**Comment by stefzi** [comment]
- [ ] Feld <summary> sichtbar machen, in xml-File vorhanden, aber wird online nicht angezeigt @chpollin

**Comment by limazangerl** [comment]
> 
> 
>     * [ ]  summary-Feld sichtbar machen, in xml-File vorhanden, aber wird online nicht angezeigt @chpollin

Bitte das dringend umsetzen
