### ISSUE TITLE
Zitierbarkeit

### ISSUE THREAD

**Issue by limazangerl** [chpollin/SZD#30]
- [x] Gibt es eine Möglichkeit, auch die Themen persistent zitierbar zu machen (siehe etwa tote Links hier: https://link.springer.com/chapter/10.1007%2F978-3-030-14600-9_2#Bib1) 
- [x] Ergänzen der bestehenden und künftiger Digitalisate um Strukturierung, damit einzelne Seiten angesteuert und zitiert werden können (wurde mehrmals angefragt)
- [x] Downloadmöglichkeit für Digitalisate

**Comment by chpollin** [comment]
@ Themen
ein redirect von o:szd.collection.1 auf o:szd.thema.1 (und so weiter) wäre notwendig.

**Comment by limazangerl** [comment]
Beide offenen Issues haben aus meiner Sicht Priorität, es wäre gut wenn wir das beides bis Ende dieser Phase implementieren könnten.
@Thema: Wäre das möglich bzw. wie aufwendig?
