### ISSUE TITLE
Fitzbauer

### ISSUE THREAD

**Issue by limazangerl** [chpollin/SZD#41]
- [x] Ingest Scans
- [x] Darstellung der Scans unter Faksimiles
- [x] Verlinkung der PIDs in SZDMSK und SZDLEB und neuer Ingest
- [x] Bild aus GitHub\webpage\img "SZD_Wurstelprater_Startbild" ingestieren
- [x] "Verschiedenes" Seite Link zum Bild anpaasen und neu ingestieren
- [x] Graphik in Slider auf Startseite ändern: Position 1 wie gehabt, 2 Wurstelprater, 3 Faksimiles
- [x] Graphiken des Sliders richtig verlinken

**Comment by limazangerl** [comment]
Für die Verlinkung der PIDs:
SZ_SEF_L1 = SZDLEB.142
SZ_SEF_L2 = SZDLEB.138
SZ_SEF_L3 = SZDLEB.139
SZ_SEF_L4 = SZDLEB.141
SZ_SEF_L5 = SZDLEB.140
SZ_SEF_L7 = SZDLEB.143
SZ_SEF_W1 = SZDMSK.352
SZ_SEF_W2 = SZDMSK.353
SZ_SEF_W3 = SZDMSK.354

**Comment by chpollin** [comment]
done
