### ISSUE TITLE
Freud falsch verlinkt

### ISSUE THREAD

**Issue by limazangerl** [chpollin/SZD#46]
Auf dieser Seite sind nicht die Briefe an Freud verlinkt, sondern Lebensdokumente: https://stefanzweig.digital/o:szd.korrespondenzen.freud-sigmund
Bitte dringend reparieren, denn dieses Konvolut wird in der Vorstellung von SZD im Kulturpool erwähnt.
@chpollin

**Comment by chpollin** [comment]
ist erledigt. Leider kann ich nicht mehr rekonstruieren, wie es dazu kam...
