### ISSUE TITLE
Beispieldaten aus Jerusalem

### ISSUE THREAD

**Issue by chpollin** [chpollin/SZD#7]
[https://glossa.uni-graz.at/o:szd.nli](url)  
- [x] Skype-Meeting mit Israel organisieren für 9/2019 @limazangerl 
- [x] nach IIIF-Daten fragen @limazangerl 
- [ ] Signaturen auf Katalogeintrag in Israel verlinken?
- [ ] IIIF für: Marie Antoinette Korrekturbögen: ARC. Ms. Var. 305 3 81, 
Der versiegelte Zug: ARC. Ms. Var. 305 3 82 
Flucht in die Unsterblichkeit: ARC. Ms. Var. 305 3 83 
- [x] IIIF für Autographen, Mail Matan
- [x] Permalinks reparieren und auf EN stellen, Nummer im Link referenziert auf Objekt.
- [x] Daten in SZDMSK ergänzen @limazangerl 
- [ ] Nummerierung der einzelnen Werkdatensätze?

**Comment by limazangerl** [comment]
Vorerst mE hinfällig, bitte zu Dokumentationszwecken aber noch behalten
